blank_issues_enabled: true
contact_links:
  - name: 'Code of conduct'
    url: https://github.com/GrayGalaxy/jiosaavn-downloader/blob/main/CODE_OF_CONDUCT.md
    about: Please follow the Code of Conduct before adding any issue.
