name: Feature request
description: Request an improvement or feature
labels: [enhancement]
assignees:
  - GrayGalaxy
body:
  - type: markdown
    attributes:
      value: |
        Request a feature that helps to add more functionality or user-experience

        - [X] Make sure to follow the [community guidllines](https://github.com/GrayGalaxy/graygalaxy/blob/main/code_of_conduct.md).
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature
      description: What would like to add as a feature?
      placeholder: |
        Explain the feature
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Suggest how to implement
      description: If you can think of some way you can apply the feature, please let us know
      placeholder: |
        Give an idea how to aply the feature
    validations:
      required: false
