name: Craete Release
env:
  DIR: build
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: Pre-release
        required: false
        type: boolean
      message:
        description: Message
        type: string
        required: false
jobs:
  Version:
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.daily-version.outputs.created }}
      version: ${{ steps.daily-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Creating release tag
        uses: fregante/daily-version-action@v1
        id: daily-version
  Build:
    needs: Version
    if: needs.Version.outputs.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Installing Dependencies
        run: yarn install
      - name: Building Package
        run: yarn build
      - name: Updating extension version
        run: >-
          npx dot-json@1 $DIR/manifest.json version ${{
          needs.Version.outputs.version }}
      - name: Creating Zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: ${{ env.DIR }}
          filename: 'release.zip'
      - name: Uploading Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ env.DIR }}/release.zip'
          artifactContentType: 'zip'
          body: ${{ github.event.inputs.message || '' }}
          prerelease: ${{ github.event.inputs.prerelease }}
          tag: ${{ needs.Version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
